import type { Doctor } from '../../models/healthcare/types';
import { dummyClinics } from './clinics';

// Helper to grab clinic(s) for a doctor
const clinicFor = (docId: string) => dummyClinics.filter((c) => c.doctorId === docId);

export const dummyDoctors: Doctor[] = [
  // ═══════════════════════════════════════════
  //  1-5 ── General Physicians
  // ═══════════════════════════════════════════
  {
    doctorId: 'doc-1',
    userId: 'user-doc-1',
    pmcNumber: 'PMC-12345-S',
    specialtyId: 'spec-1',
    subspecialties: ['Internal Medicine', 'Diabetology'],
    qualifications: ['MBBS', 'FCPS (Medicine)'],
    experience: 15,
    bio: 'Dr. Ahmed Khan is a highly experienced general physician with over 15 years of practice. He specializes in managing chronic diseases like diabetes and hypertension and has served at multiple leading hospitals in Islamabad.',
    profileImage: '',
    clinics: clinicFor('doc-1'),
    consultationFee: 2000,
    videoConsultationFee: 1500,
    rating: 4.8,
    totalReviews: 245,
    totalPatients: 3200,
    isAvailable: true,
    isVerified: true,
    verificationStatus: 'verified',
    languages: ['English', 'Urdu'],
    awards: ['Best GP Award 2022 - Pakistan Medical Association'],
    publications: [],
    createdAt: '2023-01-15T00:00:00.000Z',
  },
  {
    doctorId: 'doc-8',
    userId: 'user-doc-8',
    pmcNumber: 'PMC-88901-S',
    specialtyId: 'spec-1',
    subspecialties: ['Family Medicine', 'Preventive Medicine'],
    qualifications: ['MBBS', 'MCPS (Family Medicine)'],
    experience: 8,
    bio: 'Dr. Bilal Hussain provides holistic family medicine services with a focus on preventive care. He is known for his patient-friendly approach and thorough checkups.',
    profileImage: '',
    clinics: clinicFor('doc-8'),
    consultationFee: 1500,
    videoConsultationFee: 1000,
    rating: 4.5,
    totalReviews: 132,
    totalPatients: 1800,
    isAvailable: true,
    isVerified: true,
    verificationStatus: 'verified',
    languages: ['English', 'Urdu', 'Punjabi'],
    awards: [],
    publications: [],
    createdAt: '2024-02-10T00:00:00.000Z',
  },

  // ═══════════════════════════════════════════
  //  2 ── Cardiologists
  // ═══════════════════════════════════════════
  {
    doctorId: 'doc-2',
    userId: 'user-doc-2',
    pmcNumber: 'PMC-23456-S',
    specialtyId: 'spec-2',
    subspecialties: ['Interventional Cardiology'],
    qualifications: ['MBBS', 'FCPS (Cardiology)', 'Fellowship in Interventional Cardiology (UK)'],
    experience: 20,
    bio: 'Dr. Sara Ali is a renowned cardiologist specializing in interventional cardiology with international training from the UK. She has performed over 2,000 cardiac catheterizations.',
    profileImage: '',
    clinics: clinicFor('doc-2'),
    consultationFee: 3500,
    videoConsultationFee: 3000,
    rating: 4.9,
    totalReviews: 180,
    totalPatients: 5000,
    isAvailable: true,
    isVerified: true,
    verificationStatus: 'verified',
    languages: ['English', 'Urdu', 'Punjabi'],
    awards: ['Top Cardiologist 2023 - PCS', 'Excellence in Medicine 2021'],
    publications: ['Cardiac Interventions in Pakistan - PMJ 2022'],
    createdAt: '2022-06-10T00:00:00.000Z',
  },
  {
    doctorId: 'doc-23',
    userId: 'user-doc-23',
    pmcNumber: 'PMC-23001-S',
    specialtyId: 'spec-2',
    subspecialties: ['Electrophysiology', 'Heart Failure Management'],
    qualifications: ['MBBS', 'MRCP (UK)', 'FCPS (Cardiology)'],
    experience: 16,
    bio: 'Dr. Kamran Shahid is a cardiac electrophysiologist with advanced training from Royal Brompton Hospital, London. He specializes in complex arrhythmia management and device implantation.',
    profileImage: '',
    clinics: clinicFor('doc-23'),
    consultationFee: 4000,
    videoConsultationFee: 3000,
    rating: 4.7,
    totalReviews: 98,
    totalPatients: 2100,
    isAvailable: true,
    isVerified: true,
    verificationStatus: 'verified',
    languages: ['English', 'Urdu'],
    awards: ['Best Young Cardiologist 2020 - PSC'],
    publications: ['Electrophysiology Outcomes in South Asia - Heart Journal 2023'],
    createdAt: '2023-04-15T00:00:00.000Z',
  },
  {
    doctorId: 'doc-28',
    userId: 'user-doc-28',
    pmcNumber: 'PMC-28001-S',
    specialtyId: 'spec-2',
    subspecialties: ['Non-Invasive Cardiology'],
    qualifications: ['MBBS', 'FCPS (Cardiology)'],
    experience: 11,
    bio: 'Dr. Nadia Parveen focuses on non-invasive cardiac diagnostics including echocardiography and stress testing. She has a special interest in women\'s heart health.',
    profileImage: '',
    clinics: clinicFor('doc-28'),
    consultationFee: 3000,
    videoConsultationFee: 2500,
    rating: 4.6,
    totalReviews: 75,
    totalPatients: 1600,
    isAvailable: true,
    isVerified: true,
    verificationStatus: 'verified',
    languages: ['English', 'Urdu', 'Sindhi'],
    awards: [],
    publications: [],
    createdAt: '2024-01-20T00:00:00.000Z',
  },

  // ═══════════════════════════════════════════
  //  3 ── Dermatologists
  // ═══════════════════════════════════════════
  {
    doctorId: 'doc-3',
    userId: 'user-doc-3',
    pmcNumber: 'PMC-34567-S',
    specialtyId: 'spec-3',
    subspecialties: ['Cosmetic Dermatology', 'Laser Therapy'],
    qualifications: ['MBBS', 'FCPS (Dermatology)'],
    experience: 10,
    bio: 'Dr. Fatima Zahra specializes in skin conditions and cosmetic dermatology. She is particularly skilled in acne management, laser treatments, and chemical peels.',
    profileImage: '',
    clinics: clinicFor('doc-3'),
    consultationFee: 2500,
    videoConsultationFee: 2000,
    rating: 4.7,
    totalReviews: 312,
    totalPatients: 4100,
    isAvailable: true,
    isVerified: true,
    verificationStatus: 'verified',
    languages: ['English', 'Urdu'],
    awards: ['Best Dermatologist Islamabad 2024 - PDA'],
    publications: [],
    createdAt: '2023-03-20T00:00:00.000Z',
  },
  {
    doctorId: 'doc-17',
    userId: 'user-doc-17',
    pmcNumber: 'PMC-17001-S',
    specialtyId: 'spec-3',
    subspecialties: ['Pediatric Dermatology', 'Hair Transplant'],
    qualifications: ['MBBS', 'FCPS (Dermatology)', 'Diploma in Trichology (UK)'],
    experience: 13,
    bio: 'Dr. Zainab Malik is an expert in hair restoration and pediatric skin conditions. She has performed over 500 successful hair transplant procedures.',
    profileImage: '',
    clinics: clinicFor('doc-17'),
    consultationFee: 3000,
    videoConsultationFee: 2000,
    rating: 4.6,
    totalReviews: 198,
    totalPatients: 2800,
    isAvailable: true,
    isVerified: true,
    verificationStatus: 'verified',
    languages: ['English', 'Urdu', 'Punjabi'],
    awards: [],
    publications: ['Hair Restoration Techniques in Pakistan - PJD 2023'],
    createdAt: '2023-07-10T00:00:00.000Z',
  },

  // ═══════════════════════════════════════════
  //  4 ── Orthopedic Surgeons
  // ═══════════════════════════════════════════
  {
    doctorId: 'doc-5',
    userId: 'user-doc-5',
    pmcNumber: 'PMC-56789-S',
    specialtyId: 'spec-4',
    subspecialties: ['Sports Medicine', 'Spine Surgery'],
    qualifications: ['MBBS', 'MS (Orthopedics)', 'Fellowship in Spine Surgery (Germany)'],
    experience: 18,
    bio: 'Dr. Hassan Raza is an experienced orthopedic surgeon with expertise in sports injuries and spine conditions. He completed advanced training in Germany and has operated on national athletes.',
    profileImage: '',
    clinics: clinicFor('doc-5'),
    consultationFee: 3000,
    videoConsultationFee: 2500,
    rating: 4.5,
    totalReviews: 150,
    totalPatients: 2200,
    isAvailable: true,
    isVerified: true,
    verificationStatus: 'verified',
    languages: ['English', 'Urdu'],
    awards: ['Excellence in Sports Medicine 2023'],
    publications: ['Advances in Spine Surgery - JPOA 2021'],
    createdAt: '2022-11-15T00:00:00.000Z',
  },
  {
    doctorId: 'doc-10',
    userId: 'user-doc-10',
    pmcNumber: 'PMC-10001-S',
    specialtyId: 'spec-4',
    subspecialties: ['Joint Replacement', 'Trauma Surgery'],
    qualifications: ['MBBS', 'FCPS (Orthopedics)'],
    experience: 22,
    bio: 'Prof. Dr. Tariq Mehmood is a senior orthopedic surgeon specializing in hip and knee replacements. He has over 22 years of surgical experience and has trained numerous registrars.',
    profileImage: '',
    clinics: clinicFor('doc-10'),
    consultationFee: 3500,
    videoConsultationFee: 2500,
    rating: 4.8,
    totalReviews: 220,
    totalPatients: 4500,
    isAvailable: true,
    isVerified: true,
    verificationStatus: 'verified',
    languages: ['English', 'Urdu', 'Punjabi'],
    awards: ['Lifetime Achievement - Pakistan Orthopaedic Association 2022'],
    publications: ['Total Knee Replacement Outcomes in Pakistan - JPOA 2020'],
    createdAt: '2021-06-01T00:00:00.000Z',
  },

  // ═══════════════════════════════════════════
  //  5 ── Gynecologists
  // ═══════════════════════════════════════════
  {
    doctorId: 'doc-6',
    userId: 'user-doc-6',
    pmcNumber: 'PMC-67890-S',
    specialtyId: 'spec-5',
    subspecialties: ['High-Risk Pregnancy', 'Laparoscopic Surgery'],
    qualifications: ['MBBS', 'FCPS (Obstetrics & Gynaecology)', 'MRCOG (UK)'],
    experience: 17,
    bio: 'Dr. Amna Sheikh is a leading gynecologist in Karachi with expertise in high-risk pregnancies and minimally invasive surgeries. She completed her MRCOG from the Royal College of Obstetricians, London.',
    profileImage: '',
    clinics: clinicFor('doc-6'),
    consultationFee: 3500,
    videoConsultationFee: 2500,
    rating: 4.9,
    totalReviews: 340,
    totalPatients: 6200,
    isAvailable: true,
    isVerified: true,
    verificationStatus: 'verified',
    languages: ['English', 'Urdu', 'Sindhi'],
    awards: ['Best Gynecologist Karachi 2023 - SOGP', 'Women in Medicine Award 2021'],
    publications: ['Laparoscopic Techniques in Gynecology - JPMA 2022'],
    createdAt: '2022-03-01T00:00:00.000Z',
  },
  {
    doctorId: 'doc-11',
    userId: 'user-doc-11',
    pmcNumber: 'PMC-11001-S',
    specialtyId: 'spec-5',
    subspecialties: ['Fertility & IVF', 'PCOS Management'],
    qualifications: ['MBBS', 'FCPS (Obstetrics & Gynaecology)'],
    experience: 14,
    bio: 'Dr. Sadia Qureshi specializes in fertility treatments and PCOS management. She has helped hundreds of couples achieve successful pregnancies through IVF and other assisted reproductive techniques.',
    profileImage: '',
    clinics: clinicFor('doc-11'),
    consultationFee: 2500,
    videoConsultationFee: 2000,
    rating: 4.7,
    totalReviews: 205,
    totalPatients: 3100,
    isAvailable: true,
    isVerified: true,
    verificationStatus: 'verified',
    languages: ['English', 'Urdu', 'Punjabi'],
    awards: ['Fertility Specialist of the Year 2023'],
    publications: [],
    createdAt: '2023-01-20T00:00:00.000Z',
  },
  {
    doctorId: 'doc-24',
    userId: 'user-doc-24',
    pmcNumber: 'PMC-24001-S',
    specialtyId: 'spec-5',
    subspecialties: ['Maternal-Fetal Medicine'],
    qualifications: ['MBBS', 'FCPS (Obs & Gynae)', 'Fellowship in Maternal-Fetal Medicine (USA)'],
    experience: 19,
    bio: 'Dr. Hira Aziz is a maternal-fetal medicine specialist managing complex pregnancies. She trained at Johns Hopkins and is one of the few sub-specialists in Pakistan in this field.',
    profileImage: '',
    clinics: clinicFor('doc-24'),
    consultationFee: 4000,
    videoConsultationFee: 3000,
    rating: 4.8,
    totalReviews: 156,
    totalPatients: 2800,
    isAvailable: true,
    isVerified: true,
    verificationStatus: 'verified',
    languages: ['English', 'Urdu'],
    awards: ['Outstanding Contribution - SOGP 2022'],
    publications: ['Managing High-Risk Pregnancies in LMIC Settings - Lancet 2023'],
    createdAt: '2022-09-01T00:00:00.000Z',
  },

  // ═══════════════════════════════════════════
  //  6 ── Pediatricians
  // ═══════════════════════════════════════════
  {
    doctorId: 'doc-4',
    userId: 'user-doc-4',
    pmcNumber: 'PMC-45678-S',
    specialtyId: 'spec-6',
    subspecialties: ['Neonatology'],
    qualifications: ['MBBS', 'FCPS (Pediatrics)', 'MRCPCH (UK)'],
    experience: 12,
    bio: 'Dr. Usman Tariq is a compassionate pediatrician dedicated to child healthcare. With UK training in pediatric care, he has a special focus on neonatal and developmental medicine.',
    profileImage: '',
    clinics: clinicFor('doc-4'),
    consultationFee: 1800,
    videoConsultationFee: 1200,
    rating: 4.6,
    totalReviews: 198,
    totalPatients: 2800,
    isAvailable: true,
    isVerified: true,
    verificationStatus: 'verified',
    languages: ['English', 'Urdu', 'Punjabi'],
    awards: ['Pediatric Excellence Award 2023'],
    publications: [],
    createdAt: '2023-05-01T00:00:00.000Z',
  },
  {
    doctorId: 'doc-16',
    userId: 'user-doc-16',
    pmcNumber: 'PMC-16001-S',
    specialtyId: 'spec-6',
    subspecialties: ['Pediatric Pulmonology', 'Allergy & Immunology'],
    qualifications: ['MBBS', 'FCPS (Pediatrics)'],
    experience: 9,
    bio: 'Dr. Rabia Aslam focuses on childhood asthma, allergies, and respiratory infections. She is known for her gentle approach with young patients and detailed parent counseling.',
    profileImage: '',
    clinics: clinicFor('doc-16'),
    consultationFee: 1500,
    videoConsultationFee: 1000,
    rating: 4.4,
    totalReviews: 110,
    totalPatients: 1500,
    isAvailable: true,
    isVerified: true,
    verificationStatus: 'verified',
    languages: ['English', 'Urdu', 'Punjabi'],
    awards: [],
    publications: [],
    createdAt: '2024-03-01T00:00:00.000Z',
  },

  // ═══════════════════════════════════════════
  //  7 ── ENT Specialists
  // ═══════════════════════════════════════════
  {
    doctorId: 'doc-12',
    userId: 'user-doc-12',
    pmcNumber: 'PMC-12001-S',
    specialtyId: 'spec-7',
    subspecialties: ['Rhinology', 'Head & Neck Surgery'],
    qualifications: ['MBBS', 'FCPS (ENT)', 'Fellowship in Rhinology (Australia)'],
    experience: 14,
    bio: 'Dr. Imran Saleem is an ENT specialist with fellowship training in rhinology from Australia. He performs complex sinus and nasal surgeries using endoscopic techniques.',
    profileImage: '',
    clinics: clinicFor('doc-12'),
    consultationFee: 2500,
    videoConsultationFee: 1500,
    rating: 4.6,
    totalReviews: 142,
    totalPatients: 2400,
    isAvailable: true,
    isVerified: true,
    verificationStatus: 'verified',
    languages: ['English', 'Urdu', 'Punjabi'],
    awards: ['Best ENT Surgeon Punjab 2023'],
    publications: [],
    createdAt: '2023-02-15T00:00:00.000Z',
  },

  // ═══════════════════════════════════════════
  //  8 ── Neurologists
  // ═══════════════════════════════════════════
  {
    doctorId: 'doc-7',
    userId: 'user-doc-7',
    pmcNumber: 'PMC-78901-S',
    specialtyId: 'spec-8',
    subspecialties: ['Epilepsy', 'Stroke Medicine'],
    qualifications: ['MBBS', 'FCPS (Neurology)', 'Fellowship in Epilepsy (Canada)'],
    experience: 16,
    bio: 'Dr. Nabeel Akhtar is a neurologist with advanced fellowship in epilepsy management from the University of Toronto. He is an expert in EEG interpretation and stroke care.',
    profileImage: '',
    clinics: clinicFor('doc-7'),
    consultationFee: 3500,
    videoConsultationFee: 2500,
    rating: 4.8,
    totalReviews: 165,
    totalPatients: 3400,
    isAvailable: true,
    isVerified: true,
    verificationStatus: 'verified',
    languages: ['English', 'Urdu'],
    awards: ['Neuroscience Research Award 2022 - PNS'],
    publications: ['Epilepsy Management in Pakistan - Neurology 2023'],
    createdAt: '2022-08-20T00:00:00.000Z',
  },
  {
    doctorId: 'doc-13',
    userId: 'user-doc-13',
    pmcNumber: 'PMC-13001-S',
    specialtyId: 'spec-8',
    subspecialties: ['Movement Disorders', 'Headache Medicine'],
    qualifications: ['MBBS', 'MRCP (UK)', 'FCPS (Neurology)'],
    experience: 11,
    bio: 'Dr. Ayesha Siddiqui specializes in Parkinson\'s disease, tremors, and chronic headache disorders. She completed her MRCP from Edinburgh and brings a patient-centered approach to neurology.',
    profileImage: '',
    clinics: clinicFor('doc-13'),
    consultationFee: 3000,
    videoConsultationFee: 2500,
    rating: 4.5,
    totalReviews: 89,
    totalPatients: 1800,
    isAvailable: true,
    isVerified: true,
    verificationStatus: 'verified',
    languages: ['English', 'Urdu', 'Sindhi'],
    awards: [],
    publications: ['Headache Prevalence in Urban Pakistan - JPMA 2024'],
    createdAt: '2023-09-10T00:00:00.000Z',
  },

  // ═══════════════════════════════════════════
  //  9 ── Ophthalmologists
  // ═══════════════════════════════════════════
  {
    doctorId: 'doc-9',
    userId: 'user-doc-9',
    pmcNumber: 'PMC-90123-S',
    specialtyId: 'spec-9',
    subspecialties: ['Cataract Surgery', 'Refractive Surgery (LASIK)'],
    qualifications: ['MBBS', 'FCPS (Ophthalmology)', 'Fellowship in Refractive Surgery (USA)'],
    experience: 15,
    bio: 'Dr. Asma Khalid is a leading ophthalmologist specializing in cataract and LASIK surgeries. She trained in refractive surgery at the Wills Eye Hospital, Philadelphia.',
    profileImage: '',
    clinics: clinicFor('doc-9'),
    consultationFee: 2500,
    videoConsultationFee: 1500,
    rating: 4.7,
    totalReviews: 230,
    totalPatients: 3800,
    isAvailable: true,
    isVerified: true,
    verificationStatus: 'verified',
    languages: ['English', 'Urdu'],
    awards: ['Best Ophthalmologist Islamabad 2024'],
    publications: ['LASIK Outcomes in Pakistani Population - PJO 2023'],
    createdAt: '2022-04-10T00:00:00.000Z',
  },

  // ═══════════════════════════════════════════
  // 10 ── Urologist
  // ═══════════════════════════════════════════
  {
    doctorId: 'doc-14',
    userId: 'user-doc-14',
    pmcNumber: 'PMC-14001-S',
    specialtyId: 'spec-10',
    subspecialties: ['Kidney Stones', 'Laparoscopic Urology'],
    qualifications: ['MBBS', 'FCPS (Urology)'],
    experience: 13,
    bio: 'Dr. Faisal Rehman is a urologist with expertise in minimally invasive kidney stone removal and laparoscopic urological procedures. He has performed over 1,500 successful ESWL procedures.',
    profileImage: '',
    clinics: clinicFor('doc-14'),
    consultationFee: 2500,
    videoConsultationFee: 2000,
    rating: 4.5,
    totalReviews: 120,
    totalPatients: 2000,
    isAvailable: true,
    isVerified: true,
    verificationStatus: 'verified',
    languages: ['English', 'Urdu', 'Sindhi'],
    awards: [],
    publications: ['ESWL Outcomes - Pakistan Journal of Urology 2023'],
    createdAt: '2023-06-15T00:00:00.000Z',
  },

  // ═══════════════════════════════════════════
  // 11 ── Psychiatrists
  // ═══════════════════════════════════════════
  {
    doctorId: 'doc-15',
    userId: 'user-doc-15',
    pmcNumber: 'PMC-15001-S',
    specialtyId: 'spec-11',
    subspecialties: ['Anxiety Disorders', 'Cognitive Behavioral Therapy'],
    qualifications: ['MBBS', 'FCPS (Psychiatry)', 'MRCPsych (UK)'],
    experience: 12,
    bio: 'Dr. Mehreen Iqbal is a psychiatrist with dual fellowship and a compassionate approach to mental health. She focuses on anxiety, depression, and OCD using evidence-based therapies.',
    profileImage: '',
    clinics: clinicFor('doc-15'),
    consultationFee: 3000,
    videoConsultationFee: 2500,
    rating: 4.8,
    totalReviews: 175,
    totalPatients: 2500,
    isAvailable: true,
    isVerified: true,
    verificationStatus: 'verified',
    languages: ['English', 'Urdu'],
    awards: ['Mental Health Advocate Award 2023 - PPA'],
    publications: ['Mental Health Stigma in Pakistan - JPPS 2022'],
    createdAt: '2023-03-01T00:00:00.000Z',
  },
  {
    doctorId: 'doc-22',
    userId: 'user-doc-22',
    pmcNumber: 'PMC-22001-S',
    specialtyId: 'spec-11',
    subspecialties: ['Child Psychiatry', 'ADHD'],
    qualifications: ['MBBS', 'FCPS (Psychiatry)'],
    experience: 7,
    bio: 'Dr. Waqas Ahmed specializes in child and adolescent mental health. He focuses on ADHD, autism spectrum disorders, and behavioral issues in children.',
    profileImage: '',
    clinics: clinicFor('doc-22'),
    consultationFee: 2500,
    videoConsultationFee: 2000,
    rating: 4.4,
    totalReviews: 68,
    totalPatients: 900,
    isAvailable: true,
    isVerified: true,
    verificationStatus: 'verified',
    languages: ['English', 'Urdu'],
    awards: [],
    publications: [],
    createdAt: '2024-05-01T00:00:00.000Z',
  },

  // ═══════════════════════════════════════════
  // 12 ── Pulmonologist
  // ═══════════════════════════════════════════
  {
    doctorId: 'doc-18',
    userId: 'user-doc-18',
    pmcNumber: 'PMC-18001-S',
    specialtyId: 'spec-12',
    subspecialties: ['Interventional Pulmonology', 'Sleep Medicine'],
    qualifications: ['MBBS', 'FCPS (Pulmonology)', 'FRCP (Edinburgh)'],
    experience: 19,
    bio: 'Prof. Dr. Shahzad Alam is a leading pulmonologist and sleep medicine expert. He has pioneered interventional bronchoscopy techniques in Pakistan and heads the pulmonology department at Patel Hospital.',
    profileImage: '',
    clinics: clinicFor('doc-18'),
    consultationFee: 3000,
    videoConsultationFee: 2000,
    rating: 4.7,
    totalReviews: 145,
    totalPatients: 3200,
    isAvailable: true,
    isVerified: true,
    verificationStatus: 'verified',
    languages: ['English', 'Urdu', 'Sindhi'],
    awards: ['Best Pulmonologist Sindh 2022'],
    publications: ['Bronchoscopy Outcomes in Pakistan - Chest Journal 2021'],
    createdAt: '2022-01-10T00:00:00.000Z',
  },

  // ═══════════════════════════════════════════
  // 13 ── Gastroenterologists
  // ═══════════════════════════════════════════
  {
    doctorId: 'doc-19',
    userId: 'user-doc-19',
    pmcNumber: 'PMC-19001-S',
    specialtyId: 'spec-13',
    subspecialties: ['Hepatology', 'Endoscopy'],
    qualifications: ['MBBS', 'FCPS (Gastroenterology)', 'Fellowship in Hepatology (USA)'],
    experience: 15,
    bio: 'Dr. Saira Batool is a gastroenterologist and hepatologist with advanced training from Mount Sinai, New York. She specializes in liver diseases, endoscopic procedures, and inflammatory bowel disease.',
    profileImage: '',
    clinics: clinicFor('doc-19'),
    consultationFee: 3500,
    videoConsultationFee: 2500,
    rating: 4.6,
    totalReviews: 135,
    totalPatients: 2600,
    isAvailable: true,
    isVerified: true,
    verificationStatus: 'verified',
    languages: ['English', 'Urdu'],
    awards: ['Best GI Specialist 2023 - PSG'],
    publications: ['Hepatitis C Treatment Outcomes in Pakistan - JPMA 2022'],
    createdAt: '2023-02-01T00:00:00.000Z',
  },
  {
    doctorId: 'doc-25',
    userId: 'user-doc-25',
    pmcNumber: 'PMC-25001-S',
    specialtyId: 'spec-13',
    subspecialties: ['IBD', 'Motility Disorders'],
    qualifications: ['MBBS', 'FCPS (Medicine)', 'FCPS (Gastroenterology)'],
    experience: 10,
    bio: 'Dr. Ali Raza Gardezi focuses on inflammatory bowel disease and motility disorders. He employs the latest diagnostic techniques including capsule endoscopy.',
    profileImage: '',
    clinics: clinicFor('doc-25'),
    consultationFee: 2500,
    videoConsultationFee: 2000,
    rating: 4.3,
    totalReviews: 78,
    totalPatients: 1200,
    isAvailable: true,
    isVerified: false,
    verificationStatus: 'pending',
    languages: ['English', 'Urdu', 'Punjabi'],
    awards: [],
    publications: [],
    createdAt: '2024-06-01T00:00:00.000Z',
  },

  // ═══════════════════════════════════════════
  // 14 ── Endocrinologists
  // ═══════════════════════════════════════════
  {
    doctorId: 'doc-20',
    userId: 'user-doc-20',
    pmcNumber: 'PMC-20001-S',
    specialtyId: 'spec-14',
    subspecialties: ['Diabetes Management', 'Thyroid Disorders'],
    qualifications: ['MBBS', 'FCPS (Endocrinology)'],
    experience: 11,
    bio: 'Dr. Noman Akbar is an endocrinologist focused on diabetes, thyroid, and metabolic disorders. He manages a high-volume diabetes clinic and is passionate about patient education and lifestyle modification.',
    profileImage: '',
    clinics: clinicFor('doc-20'),
    consultationFee: 2500,
    videoConsultationFee: 2000,
    rating: 4.5,
    totalReviews: 165,
    totalPatients: 2900,
    isAvailable: true,
    isVerified: true,
    verificationStatus: 'verified',
    languages: ['English', 'Urdu', 'Punjabi'],
    awards: ['Diabetes Educator of the Year 2024'],
    publications: ['Diabetes Prevalence in Urban Punjab - JDEP 2023'],
    createdAt: '2023-08-01T00:00:00.000Z',
  },
  {
    doctorId: 'doc-26',
    userId: 'user-doc-26',
    pmcNumber: 'PMC-26001-S',
    specialtyId: 'spec-14',
    subspecialties: ['Obesity Medicine', 'PCOS Endocrinology'],
    qualifications: ['MBBS', 'MRCP (UK)', 'SCE Endocrinology (UK)'],
    experience: 9,
    bio: 'Dr. Sana Riaz specializes in obesity management and hormonal disorders, particularly PCOS-related metabolic issues. She brings a UK-trained approach with focus on evidence-based protocols.',
    profileImage: '',
    clinics: clinicFor('doc-26'),
    consultationFee: 2000,
    videoConsultationFee: 1500,
    rating: 4.4,
    totalReviews: 92,
    totalPatients: 1400,
    isAvailable: true,
    isVerified: true,
    verificationStatus: 'verified',
    languages: ['English', 'Urdu'],
    awards: [],
    publications: [],
    createdAt: '2024-02-15T00:00:00.000Z',
  },

  // ═══════════════════════════════════════════
  // 15 ── Nephrologists
  // ═══════════════════════════════════════════
  {
    doctorId: 'doc-21',
    userId: 'user-doc-21',
    pmcNumber: 'PMC-21001-S',
    specialtyId: 'spec-15',
    subspecialties: ['Dialysis', 'Transplant Nephrology'],
    qualifications: ['MBBS', 'FCPS (Nephrology)', 'Fellowship in Transplant Nephrology (USA)'],
    experience: 17,
    bio: 'Dr. Rizwan ul Haq is a senior nephrologist and transplant specialist. He manages one of the largest dialysis units in Islamabad and has been involved in over 200 kidney transplant cases.',
    profileImage: '',
    clinics: clinicFor('doc-21'),
    consultationFee: 3000,
    videoConsultationFee: 2000,
    rating: 4.7,
    totalReviews: 110,
    totalPatients: 1800,
    isAvailable: true,
    isVerified: true,
    verificationStatus: 'verified',
    languages: ['English', 'Urdu', 'Pashto'],
    awards: ['Best Nephrologist Pakistan 2023 - PSN'],
    publications: ['Kidney Transplant Outcomes in Pakistan - PKJ 2022'],
    createdAt: '2022-07-01T00:00:00.000Z',
  },

  // ═══════════════════════════════════════════
  //  Additional doctors to reach 30
  // ═══════════════════════════════════════════
  {
    doctorId: 'doc-27',
    userId: 'user-doc-27',
    pmcNumber: 'PMC-27001-S',
    specialtyId: 'spec-7',
    subspecialties: ['Otology', 'Cochlear Implants'],
    qualifications: ['MBBS', 'MS (ENT)'],
    experience: 6,
    bio: 'Dr. Hamza Butt is a young ENT surgeon with a focus on ear surgeries and hearing restoration. He\'s rapidly building a reputation for excellent surgical outcomes.',
    profileImage: '',
    clinics: clinicFor('doc-27'),
    consultationFee: 1500,
    videoConsultationFee: 1000,
    rating: 4.2,
    totalReviews: 45,
    totalPatients: 600,
    isAvailable: true,
    isVerified: true,
    verificationStatus: 'verified',
    languages: ['English', 'Urdu', 'Punjabi'],
    awards: [],
    publications: [],
    createdAt: '2024-08-01T00:00:00.000Z',
  },
  {
    doctorId: 'doc-29',
    userId: 'user-doc-29',
    pmcNumber: 'PMC-29001-S',
    specialtyId: 'spec-9',
    subspecialties: ['Retina', 'Vitreous Surgery'],
    qualifications: ['MBBS', 'FCPS (Ophthalmology)', 'Fellowship in Retinal Surgery (Singapore)'],
    experience: 14,
    bio: 'Dr. Adeel Farooq is a retinal surgeon trained in Singapore. He specializes in diabetic retinopathy, macular degeneration, and complex vitreo-retinal surgeries.',
    profileImage: '',
    clinics: clinicFor('doc-29'),
    consultationFee: 3500,
    videoConsultationFee: 2000,
    rating: 4.7,
    totalReviews: 130,
    totalPatients: 2200,
    isAvailable: true,
    isVerified: true,
    verificationStatus: 'verified',
    languages: ['English', 'Urdu', 'Punjabi'],
    awards: ['Best Retinal Surgeon Award 2023 - POS'],
    publications: ['Vitrectomy Outcomes in Pakistan - PJO 2024'],
    createdAt: '2023-05-20T00:00:00.000Z',
  },
  {
    doctorId: 'doc-30',
    userId: 'user-doc-30',
    pmcNumber: 'PMC-30001-S',
    specialtyId: 'spec-12',
    subspecialties: ['Tuberculosis', 'Chronic Cough'],
    qualifications: ['MBBS', 'DTCD', 'FCPS (Pulmonology)'],
    experience: 20,
    bio: 'Dr. Khalid Mehmood is a veteran pulmonologist with two decades of experience, particularly in TB management and chronic respiratory diseases. He heads the pulmonology department at his hospital.',
    profileImage: '',
    clinics: clinicFor('doc-30'),
    consultationFee: 2000,
    videoConsultationFee: 1500,
    rating: 4.4,
    totalReviews: 185,
    totalPatients: 4200,
    isAvailable: false,
    isVerified: true,
    verificationStatus: 'verified',
    languages: ['English', 'Urdu', 'Pashto'],
    awards: ['TB Control Champion Award 2021 - WHO Pakistan'],
    publications: ['TB Treatment Adherence in Pakistan - IJRD 2020'],
    createdAt: '2021-11-01T00:00:00.000Z',
  },
];

// Helper to look up doctors by specialty
export const getDoctorsBySpecialty = (specialtyId: string): Doctor[] =>
  dummyDoctors.filter((d) => d.specialtyId === specialtyId);

// Helper to look up a doctor by ID
export const getDoctorById = (doctorId: string): Doctor | undefined =>
  dummyDoctors.find((d) => d.doctorId === doctorId);
