import type { Specialty } from '../../models/healthcare/types';

export const dummySpecialties: Specialty[] = [
  {
    specialtyId: 'spec-1',
    name: 'General Physician',
    icon: 'stethoscope',
    description: 'Primary care, diagnosis, and treatment of common illnesses',
    doctorCount: 48,
    commonConditions: ['Fever', 'Cold & Flu', 'Infections', 'Diabetes', 'Hypertension', 'Typhoid'],
    isActive: true,
  },
  {
    specialtyId: 'spec-2',
    name: 'Cardiologist',
    icon: 'heart-pulse',
    description: 'Heart and cardiovascular system disorders',
    doctorCount: 22,
    commonConditions: ['Heart Disease', 'Chest Pain', 'High Blood Pressure', 'Arrhythmia', 'Heart Failure'],
    isActive: true,
  },
  {
    specialtyId: 'spec-3',
    name: 'Dermatologist',
    icon: 'hand',
    description: 'Skin, hair, and nail conditions',
    doctorCount: 26,
    commonConditions: ['Acne', 'Eczema', 'Psoriasis', 'Hair Loss', 'Skin Allergies', 'Fungal Infections'],
    isActive: true,
  },
  {
    specialtyId: 'spec-4',
    name: 'Orthopedic Surgeon',
    icon: 'bone',
    description: 'Bones, joints, ligaments, and muscles',
    doctorCount: 18,
    commonConditions: ['Back Pain', 'Fractures', 'Arthritis', 'Joint Pain', 'Sports Injuries', 'Disc Problems'],
    isActive: true,
  },
  {
    specialtyId: 'spec-5',
    name: 'Gynecologist',
    icon: 'baby',
    description: "Women's reproductive health and pregnancy care",
    doctorCount: 30,
    commonConditions: ['Pregnancy', 'PCOS', 'Menstrual Disorders', 'Infertility', 'Fibroids', 'Endometriosis'],
    isActive: true,
  },
  {
    specialtyId: 'spec-6',
    name: 'Pediatrician',
    icon: 'smile',
    description: 'Healthcare for infants, children, and adolescents',
    doctorCount: 34,
    commonConditions: ['Child Fever', 'Growth Issues', 'Vaccinations', 'Allergies', 'Asthma', 'Nutritional Deficiency'],
    isActive: true,
  },
  {
    specialtyId: 'spec-7',
    name: 'ENT Specialist',
    icon: 'ear',
    description: 'Ear, nose, and throat disorders',
    doctorCount: 14,
    commonConditions: ['Ear Infection', 'Sinusitis', 'Tonsillitis', 'Hearing Loss', 'Nasal Polyps', 'Vertigo'],
    isActive: true,
  },
  {
    specialtyId: 'spec-8',
    name: 'Neurologist',
    icon: 'brain',
    description: 'Brain, spinal cord, and nervous system',
    doctorCount: 12,
    commonConditions: ['Migraine', 'Epilepsy', 'Stroke', 'Neuropathy', 'Parkinson\'s Disease', 'Multiple Sclerosis'],
    isActive: true,
  },
  {
    specialtyId: 'spec-9',
    name: 'Ophthalmologist',
    icon: 'eye',
    description: 'Eye diseases and vision care',
    doctorCount: 20,
    commonConditions: ['Cataract', 'Glaucoma', 'Myopia', 'Dry Eyes', 'Diabetic Retinopathy', 'Conjunctivitis'],
    isActive: true,
  },
  {
    specialtyId: 'spec-10',
    name: 'Urologist',
    icon: 'medical',
    description: 'Urinary tract and male reproductive system',
    doctorCount: 10,
    commonConditions: ['Kidney Stones', 'UTI', 'Prostate Issues', 'Incontinence', 'Bladder Problems'],
    isActive: true,
  },
  {
    specialtyId: 'spec-11',
    name: 'Psychiatrist',
    icon: 'chatbubbles',
    description: 'Mental health and behavioral disorders',
    doctorCount: 16,
    commonConditions: ['Depression', 'Anxiety', 'OCD', 'Bipolar Disorder', 'PTSD', 'Insomnia'],
    isActive: true,
  },
  {
    specialtyId: 'spec-12',
    name: 'Pulmonologist',
    icon: 'fitness',
    description: 'Lungs and respiratory system',
    doctorCount: 11,
    commonConditions: ['Asthma', 'COPD', 'Pneumonia', 'TB', 'Sleep Apnea', 'Bronchitis'],
    isActive: true,
  },
  {
    specialtyId: 'spec-13',
    name: 'Gastroenterologist',
    icon: 'nutrition',
    description: 'Digestive system and liver disorders',
    doctorCount: 15,
    commonConditions: ['Gastritis', 'IBS', 'Hepatitis', 'Ulcers', 'GERD', 'Crohn\'s Disease'],
    isActive: true,
  },
  {
    specialtyId: 'spec-14',
    name: 'Endocrinologist',
    icon: 'pulse',
    description: 'Hormonal and metabolic disorders',
    doctorCount: 9,
    commonConditions: ['Diabetes', 'Thyroid Disorders', 'Obesity', 'PCOS', 'Osteoporosis', 'Adrenal Disorders'],
    isActive: true,
  },
  {
    specialtyId: 'spec-15',
    name: 'Nephrologist',
    icon: 'water',
    description: 'Kidney diseases and dialysis care',
    doctorCount: 8,
    commonConditions: ['Chronic Kidney Disease', 'Kidney Stones', 'Dialysis', 'Nephritis', 'Kidney Failure'],
    isActive: true,
  },
];
