// ============================================
// DUMMY DATA FOR SERVICE PROVIDERS
// ============================================

import {
  Provider,
  SavedAddress,
  TimeSlot,
} from '../../models/serviceProviders';

export const DUMMY_PROVIDERS: Provider[] = [
  {
    id: '1',
    name: 'John Smith',
    image: 'https://randomuser.me/api/portraits/men/1.jpg',
    email: 'john.smith@email.com',
    phoneNumber: '+92 300 1234567',
    rating: 4.9,
    reviews: 156,
    experience: '8 years',
    price: 1500,
    verified: true,
    available: true,
    isOnline: true,
    responseTime: '~15 min',
    specialty: 'Wiring & Installations',
    bio: 'Expert electrician with over 8 years of experience in residential and commercial electrical work.',
    address: 'Gulberg III, Lahore',
    city: 'Lahore',
    category: 'electricians',
    skills: ['Wiring', 'Installations', 'Repairs', 'Safety Inspections'],
    certifications: ['Licensed Electrician', 'Safety Certified'],
    languages: ['English', 'Urdu'],
    completedJobs: 456,
    jobSuccessRate: 98,
    coordinates: { latitude: 31.5204, longitude: 74.3587 },
    createdAt: '2023-01-15T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z',
  },
  {
    id: '2',
    name: 'Ahmed Khan',
    image: 'https://randomuser.me/api/portraits/men/2.jpg',
    email: 'ahmed.khan@email.com',
    phoneNumber: '+92 300 2345678',
    rating: 4.8,
    reviews: 89,
    experience: '5 years',
    price: 1200,
    verified: true,
    available: true,
    isOnline: false,
    responseTime: '~30 min',
    specialty: 'Pipe Repairs',
    bio: 'Professional plumber specializing in emergency repairs and installations.',
    address: 'DHA Phase 5, Lahore',
    city: 'Lahore',
    category: 'plumbers',
    skills: ['Pipe Repairs', 'Installations', 'Drainage'],
    certifications: ['Professional Plumber'],
    languages: ['English', 'Urdu'],
    completedJobs: 234,
    jobSuccessRate: 96,
    coordinates: { latitude: 31.4697, longitude: 74.4077 },
    createdAt: '2023-03-20T00:00:00Z',
    updatedAt: '2024-01-10T00:00:00Z',
  },
  {
    id: '3',
    name: 'Ali Hassan',
    image: 'https://randomuser.me/api/portraits/men/3.jpg',
    email: 'ali.hassan@email.com',
    phoneNumber: '+92 300 3456789',
    rating: 4.7,
    reviews: 67,
    experience: '6 years',
    price: 2000,
    verified: true,
    available: true,
    isOnline: true,
    responseTime: '~20 min',
    specialty: 'AC Installation & Repair',
    bio: 'Certified AC technician with expertise in all major brands.',
    address: 'Model Town, Lahore',
    city: 'Lahore',
    category: 'ac-repairers',
    skills: ['AC Installation', 'AC Repair', 'Maintenance', 'Gas Filling'],
    certifications: ['HVAC Certified'],
    languages: ['English', 'Urdu', 'Punjabi'],
    completedJobs: 189,
    jobSuccessRate: 97,
    coordinates: { latitude: 31.4833, longitude: 74.3172 },
    createdAt: '2023-02-10T00:00:00Z',
    updatedAt: '2024-01-12T00:00:00Z',
  },
];

export const DUMMY_SAVED_ADDRESSES: SavedAddress[] = [
  {
    id: '1',
    label: 'Home',
    address: '123 Main Street, Gulberg III, Lahore',
    icon: 'home',
    isDefault: true,
    coordinates: { latitude: 31.5204, longitude: 74.3587 },
  },
  {
    id: '2',
    label: 'Office',
    address: '456 Business Avenue, DHA Phase 5, Lahore',
    icon: 'briefcase',
    isDefault: false,
    coordinates: { latitude: 31.4697, longitude: 74.4077 },
  },
];

export const DUMMY_TIME_SLOTS: TimeSlot[] = [
  { id: '1', time: '09:00 AM', available: true, period: 'morning' },
  { id: '2', time: '10:00 AM', available: true, period: 'morning' },
  { id: '3', time: '11:00 AM', available: false, period: 'morning' },
  { id: '4', time: '12:00 PM', available: true, period: 'afternoon' },
  { id: '5', time: '01:00 PM', available: true, period: 'afternoon' },
  { id: '6', time: '02:00 PM', available: true, period: 'afternoon' },
  { id: '7', time: '03:00 PM', available: false, period: 'afternoon' },
  { id: '8', time: '04:00 PM', available: true, period: 'evening' },
  { id: '9', time: '05:00 PM', available: true, period: 'evening' },
  { id: '10', time: '06:00 PM', available: true, period: 'evening' },
];
