import type { BrandConfig } from '../../types/shopping';

export const DUMMY_BRANDS: BrandConfig[] = [
  {
    brandId: 'brand-outfitters',
    odexId: 'odex-outfitters',
    name: 'Outfitters',
    slug: 'outfitters',
    description: 'Pakistan\'s leading fashion retail brand offering trendy apparel for men and women.',
    tagline: 'Express Yourself',
    logo: 'https://placehold.co/200x200/FF6B35/FFF?text=OTF',
    bannerImage: 'https://placehold.co/800x400/FF6B35/FFF?text=Outfitters',
    primaryColor: '#FF6B35',
    secondaryColor: '#FFB088',
    accentColor: '#E65100',
    categories: ['Men', 'Women', 'Accessories'],
    policies: {
      returnDays: 15,
      shippingInfo: 'Free shipping on orders above PKR 3,000. Delivery within 3-5 business days.',
      paymentMethods: ['COD', 'Credit Card', 'JazzCash', 'Easypaisa'],
    },
    contactEmail: 'support@outfitters.com.pk',
    contactPhone: '+92-42-111-688-348',
    website: 'https://outfitters.com.pk',
    socialLinks: {
      facebook: 'https://facebook.com/outfitterspk',
      instagram: 'https://instagram.com/outfitterspk',
    },
    isActive: true,
    createdAt: '2024-01-15T10:00:00Z',
  },
  {
    brandId: 'brand-khaadi',
    odexId: 'odex-khaadi',
    name: 'Khaadi',
    slug: 'khaadi',
    description: 'Iconic Pakistani fashion brand known for handcrafted fabrics and contemporary designs.',
    tagline: 'Weaving Dreams',
    logo: 'https://placehold.co/200x200/8B0000/FFF?text=KH',
    bannerImage: 'https://placehold.co/800x400/8B0000/FFF?text=Khaadi',
    primaryColor: '#8B0000',
    secondaryColor: '#CD5C5C',
    accentColor: '#A52A2A',
    categories: ['Women', 'Unstitched', 'Home', 'Kids'],
    policies: {
      returnDays: 14,
      shippingInfo: 'Free shipping on orders above PKR 5,000. Delivery within 3-7 business days.',
      paymentMethods: ['COD', 'Credit Card', 'Debit Card', 'JazzCash'],
    },
    contactEmail: 'care@khaadi.com',
    contactPhone: '+92-21-111-542-234',
    website: 'https://khaadi.com',
    socialLinks: {
      facebook: 'https://facebook.com/khaadi',
      instagram: 'https://instagram.com/khaadi',
      tiktok: 'https://tiktok.com/@khaadi',
    },
    isActive: true,
    createdAt: '2024-01-10T10:00:00Z',
  },
  {
    brandId: 'brand-gulahmed',
    odexId: 'odex-gulahmed',
    name: 'Gul Ahmed',
    slug: 'gul-ahmed',
    description: 'One of Pakistan\'s most trusted textile brands offering premium fabrics and fashion.',
    tagline: 'Ideas that Inspire',
    logo: 'https://placehold.co/200x200/1E4D92/FFF?text=GA',
    bannerImage: 'https://placehold.co/800x400/1E4D92/FFF?text=Gul+Ahmed',
    primaryColor: '#1E4D92',
    secondaryColor: '#5B8AC7',
    accentColor: '#0D3B7A',
    categories: ['Women', 'Men', 'Kids', 'Unstitched', 'Home'],
    policies: {
      returnDays: 14,
      shippingInfo: 'Free delivery on orders above PKR 4,000. Standard delivery 3-5 days.',
      paymentMethods: ['COD', 'Credit Card', 'Debit Card', 'Bank Transfer'],
    },
    contactEmail: 'customercare@gulahmed.com',
    contactPhone: '+92-21-111-485-243',
    website: 'https://gulahmed.com',
    socialLinks: {
      facebook: 'https://facebook.com/gulahmedshop',
      instagram: 'https://instagram.com/gulahmedshop',
    },
    isActive: true,
    createdAt: '2024-01-08T10:00:00Z',
  },
  {
    brandId: 'brand-beechtree',
    odexId: 'odex-beechtree',
    name: 'Beechtree',
    slug: 'beechtree',
    description: 'Contemporary women\'s fashion brand focused on modern, chic Pakistani styles.',
    tagline: 'Be Your Own Kind',
    logo: 'https://placehold.co/200x200/E91E63/FFF?text=BT',
    bannerImage: 'https://placehold.co/800x400/E91E63/FFF?text=Beechtree',
    primaryColor: '#E91E63',
    secondaryColor: '#F48FB1',
    accentColor: '#C2185B',
    categories: ['Women', 'Girls', 'Accessories'],
    policies: {
      returnDays: 10,
      shippingInfo: 'Free shipping above PKR 2,500. Delivery in 2-5 business days.',
      paymentMethods: ['COD', 'Credit Card', 'Easypaisa'],
    },
    contactEmail: 'hello@beechtree.pk',
    contactPhone: '+92-42-111-233-248',
    website: 'https://beechtree.pk',
    socialLinks: {
      facebook: 'https://facebook.com/beechtreepk',
      instagram: 'https://instagram.com/beechtreepk',
    },
    isActive: true,
    createdAt: '2024-02-01T10:00:00Z',
  },
  {
    brandId: 'brand-ideas',
    odexId: 'odex-ideas',
    name: 'Ideas by Gul Ahmed',
    slug: 'ideas',
    description: 'Lifestyle brand offering ready-to-wear fashion, home textiles, and fragrances.',
    tagline: 'Pret, Home & More',
    logo: 'https://placehold.co/200x200/4CAF50/FFF?text=ID',
    bannerImage: 'https://placehold.co/800x400/4CAF50/FFF?text=Ideas',
    primaryColor: '#4CAF50',
    secondaryColor: '#81C784',
    accentColor: '#388E3C',
    categories: ['Women', 'Men', 'Kids', 'Home', 'Fragrances'],
    policies: {
      returnDays: 14,
      shippingInfo: 'Free shipping on orders above PKR 3,500. Delivery 3-7 days nationwide.',
      paymentMethods: ['COD', 'Credit Card', 'Debit Card', 'JazzCash', 'Easypaisa'],
    },
    contactEmail: 'support@gulahmedideas.com',
    contactPhone: '+92-21-111-432-432',
    website: 'https://ideas.com.pk',
    socialLinks: {
      facebook: 'https://facebook.com/ideaspakistan',
      instagram: 'https://instagram.com/ideaspakistan',
      youtube: 'https://youtube.com/@ideaspakistan',
    },
    isActive: true,
    createdAt: '2024-01-20T10:00:00Z',
  },
];
