import type { Category } from '../../types/shopping';

export const DUMMY_CATEGORIES: Category[] = [
  {
    categoryId: 'cat-men',
    name: 'Men',
    slug: 'men',
    icon: '👔',
    productCount: 120,
    children: [
      {
        categoryId: 'cat-men-shirts',
        name: 'Shirts',
        slug: 'men-shirts',
        icon: '👕',
        parentId: 'cat-men',
        productCount: 35,
        children: [],
      },
      {
        categoryId: 'cat-men-trousers',
        name: 'Trousers & Jeans',
        slug: 'men-trousers',
        icon: '👖',
        parentId: 'cat-men',
        productCount: 28,
        children: [],
      },
      {
        categoryId: 'cat-men-tshirts',
        name: 'T-Shirts & Polos',
        slug: 'men-tshirts',
        icon: '🎽',
        parentId: 'cat-men',
        productCount: 32,
        children: [],
      },
      {
        categoryId: 'cat-men-kurta',
        name: 'Kurta & Shalwar Kameez',
        slug: 'men-kurta',
        icon: '🧥',
        parentId: 'cat-men',
        productCount: 25,
        children: [],
      },
    ],
  },
  {
    categoryId: 'cat-women',
    name: 'Women',
    slug: 'women',
    icon: '👗',
    productCount: 200,
    children: [
      {
        categoryId: 'cat-women-kurti',
        name: 'Kurti & Tops',
        slug: 'women-kurti',
        icon: '👚',
        parentId: 'cat-women',
        productCount: 55,
        children: [],
      },
      {
        categoryId: 'cat-women-unstitched',
        name: 'Unstitched Fabric',
        slug: 'women-unstitched',
        icon: '🧶',
        parentId: 'cat-women',
        productCount: 45,
        children: [],
      },
      {
        categoryId: 'cat-women-ready',
        name: 'Ready to Wear',
        slug: 'women-ready',
        icon: '👘',
        parentId: 'cat-women',
        productCount: 50,
        children: [],
      },
      {
        categoryId: 'cat-women-scarves',
        name: 'Dupattas & Scarves',
        slug: 'women-scarves',
        icon: '🧣',
        parentId: 'cat-women',
        productCount: 30,
        children: [],
      },
      {
        categoryId: 'cat-women-bottoms',
        name: 'Trousers & Pants',
        slug: 'women-bottoms',
        icon: '👖',
        parentId: 'cat-women',
        productCount: 20,
        children: [],
      },
    ],
  },
  {
    categoryId: 'cat-kids',
    name: 'Kids',
    slug: 'kids',
    icon: '🧒',
    productCount: 80,
    children: [
      {
        categoryId: 'cat-kids-boys',
        name: 'Boys',
        slug: 'kids-boys',
        icon: '👦',
        parentId: 'cat-kids',
        productCount: 40,
        children: [],
      },
      {
        categoryId: 'cat-kids-girls',
        name: 'Girls',
        slug: 'kids-girls',
        icon: '👧',
        parentId: 'cat-kids',
        productCount: 40,
        children: [],
      },
    ],
  },
  {
    categoryId: 'cat-shoes',
    name: 'Shoes',
    slug: 'shoes',
    icon: '👟',
    productCount: 60,
    children: [
      {
        categoryId: 'cat-shoes-men',
        name: "Men's Shoes",
        slug: 'shoes-men',
        icon: '👞',
        parentId: 'cat-shoes',
        productCount: 25,
        children: [],
      },
      {
        categoryId: 'cat-shoes-women',
        name: "Women's Shoes",
        slug: 'shoes-women',
        icon: '👠',
        parentId: 'cat-shoes',
        productCount: 25,
        children: [],
      },
      {
        categoryId: 'cat-shoes-sports',
        name: 'Sports & Sneakers',
        slug: 'shoes-sports',
        icon: '🏃',
        parentId: 'cat-shoes',
        productCount: 10,
        children: [],
      },
    ],
  },
  {
    categoryId: 'cat-home',
    name: 'Home',
    slug: 'home',
    icon: '🏠',
    productCount: 50,
    children: [
      {
        categoryId: 'cat-home-bedding',
        name: 'Bedding',
        slug: 'home-bedding',
        icon: '🛏️',
        parentId: 'cat-home',
        productCount: 20,
        children: [],
      },
      {
        categoryId: 'cat-home-towels',
        name: 'Towels & Bath',
        slug: 'home-towels',
        icon: '🛁',
        parentId: 'cat-home',
        productCount: 15,
        children: [],
      },
      {
        categoryId: 'cat-home-cushions',
        name: 'Cushions & Throws',
        slug: 'home-cushions',
        icon: '🛋️',
        parentId: 'cat-home',
        productCount: 15,
        children: [],
      },
    ],
  },
];
